"""Static HTML report generator for GitHub Pages deployment.

Converts markdown reports into a clean HTML site with an index page.

Usage:
    python -m ai_financial_advisor.web.static_generator --output-dir docs/site
"""

import logging
from pathlib import Path

from jinja2 import Template

logger = logging.getLogger(__name__)

_INDEX_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Financial Advisor — Daily Reports</title>
    <style>
        :root { --bg: #f8f9fa; --card: #fff; --text: #212529; --accent: #0d6efd; --border: #dee2e6; }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               background: var(--bg); color: var(--text); line-height: 1.6; padding: 2rem; max-width: 900px; margin: 0 auto; }
        h1 { margin-bottom: 0.5rem; }
        .subtitle { color: #6c757d; margin-bottom: 2rem; }
        .report-list { list-style: none; }
        .report-list li { background: var(--card); border: 1px solid var(--border); border-radius: 8px;
                          padding: 1rem 1.5rem; margin-bottom: 0.75rem; }
        .report-list a { color: var(--accent); text-decoration: none; font-weight: 500; font-size: 1.1rem; }
        .report-list a:hover { text-decoration: underline; }
        .report-list .date { color: #6c757d; font-size: 0.9rem; margin-left: 0.5rem; }
        footer { margin-top: 3rem; color: #6c757d; font-size: 0.85rem; text-align: center; }
    </style>
</head>
<body>
    <h1>AI Financial Advisor</h1>
    <p class="subtitle">Daily Global News Reports — auto-generated by AI</p>
    <ul class="report-list">
    {% for report in reports %}
        <li>
            <a href="{{ report.filename }}">{{ report.title }}</a>
            <span class="date">{{ report.date }}</span>
        </li>
    {% endfor %}
    </ul>
    {% if not reports %}
    <p>No reports available yet. Run <code>ai-advisor news run</code> to generate.</p>
    {% endif %}
    <footer>Powered by AI Financial Advisor &middot; Updated daily via GitHub Actions</footer>
</body>
</html>
""")

_REPORT_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        :root { --bg: #f8f9fa; --card: #fff; --text: #212529; --accent: #0d6efd; --border: #dee2e6; }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               background: var(--bg); color: var(--text); line-height: 1.7; padding: 2rem; max-width: 900px; margin: 0 auto; }
        .content { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 2rem; }
        h1 { margin-bottom: 1.5rem; font-size: 1.5rem; }
        h2 { margin: 1.5rem 0 0.75rem; color: var(--accent); }
        h3 { margin: 1rem 0 0.5rem; }
        p, li { margin-bottom: 0.5rem; }
        ul, ol { padding-left: 1.5rem; }
        a { color: var(--accent); }
        .back { display: inline-block; margin-bottom: 1rem; color: var(--accent); text-decoration: none; }
        .back:hover { text-decoration: underline; }
        strong { color: #495057; }
        code { background: #e9ecef; padding: 0.15em 0.4em; border-radius: 3px; font-size: 0.9em; }
        hr { border: none; border-top: 1px solid var(--border); margin: 1.5rem 0; }
        table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
        th, td { border: 1px solid var(--border); padding: 0.5rem 0.75rem; text-align: left; }
        th { background: #f1f3f5; }
    </style>
</head>
<body>
    <a class="back" href="index.html">&larr; Back to all reports</a>
    <div class="content">
        {{ content_html }}
    </div>
</body>
</html>
""")


def _markdown_to_html(md: str) -> str:
    """Basic markdown to HTML conversion without external dependencies.

    Handles headings, bold, links, lists, horizontal rules, and paragraphs.
    For production use, consider replacing with `markdown` or `mistune`.
    """
    import re

    lines = md.split("\n")
    html_lines: list[str] = []
    in_list = False

    for line in lines:
        stripped = line.strip()

        # Horizontal rule
        if stripped in ("---", "***", "___"):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append("<hr>")
            continue

        # Headings
        heading_match = re.match(r"^(#{1,6})\s+(.*)", stripped)
        if heading_match:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            level = len(heading_match.group(1))
            text = heading_match.group(2)
            html_lines.append(f"<h{level}>{_inline_format(text)}</h{level}>")
            continue

        # List items
        list_match = re.match(r"^[-*]\s+(.*)", stripped)
        if list_match:
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            html_lines.append(f"<li>{_inline_format(list_match.group(1))}</li>")
            continue

        # Numbered list
        num_match = re.match(r"^\d+[.)]\s+(.*)", stripped)
        if num_match:
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            html_lines.append(f"<li>{_inline_format(num_match.group(1))}</li>")
            continue

        # Close list if needed
        if in_list and not stripped:
            html_lines.append("</ul>")
            in_list = False
            continue

        # Empty line
        if not stripped:
            continue

        # Paragraph
        if in_list:
            html_lines.append("</ul>")
            in_list = False
        html_lines.append(f"<p>{_inline_format(stripped)}</p>")

    if in_list:
        html_lines.append("</ul>")

    return "\n".join(html_lines)


def _inline_format(text: str) -> str:
    """Apply inline markdown formatting: bold, links, code."""
    import re

    # Code spans
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    # Bold
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    # Links
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    return text


def generate_static_site(
    reports_dir: Path,
    output_dir: Path,
) -> None:
    """Generate a static HTML site from markdown reports.

    Args:
        reports_dir: Directory containing NR_*.md report files.
        output_dir: Directory to write the HTML files to.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    report_files = sorted(reports_dir.glob("NR_*.md"), reverse=True)
    logger.info("Found %d report files in %s", len(report_files), reports_dir)

    index_entries = []

    for md_file in report_files:
        md_content = md_file.read_text(encoding="utf-8")

        # Extract title from first line
        first_line = md_content.split("\n", 1)[0].lstrip("# ").strip()
        title = first_line or md_file.stem

        # Extract date from filename (NR_YYYY-MM-DD.md)
        date_str = md_file.stem.replace("NR_", "").replace("_CN", "").replace("_EN", "")

        content_html = _markdown_to_html(md_content)
        html_filename = md_file.stem + ".html"

        # Write individual report page
        report_html = _REPORT_TEMPLATE.render(
            title=title,
            content_html=content_html,
        )
        (output_dir / html_filename).write_text(report_html, encoding="utf-8")

        index_entries.append({
            "filename": html_filename,
            "title": title,
            "date": date_str,
        })

    # Write index page
    index_html = _INDEX_TEMPLATE.render(reports=index_entries)
    (output_dir / "index.html").write_text(index_html, encoding="utf-8")

    logger.info("Static site generated: %d pages in %s", len(report_files) + 1, output_dir)


def main() -> None:
    """CLI entry point for static site generation."""
    import argparse

    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser(description="Generate static HTML from news reports.")
    parser.add_argument("--reports-dir", type=Path, default=Path("data/reports"))
    parser.add_argument("--output-dir", type=Path, default=Path("docs/site"))
    args = parser.parse_args()

    generate_static_site(args.reports_dir, args.output_dir)


if __name__ == "__main__":
    main()
